### ISSUE TITLE
OSI library import not working in Python 3

### ISSUE THREAD

**Issue by jr7** [OpenSimulationInterface/open-simulation-interface#243] opened 2018-05-30 07:42 UTC
Hello, 

the OSI Library for Python3 is not working on my computer,
was this tested before ? what is the default Python version you are using ? 

For example `import osi.osi_sensordata_pb2`  will give an Exeception :

    ModuleNotFoundError: No module named 'osi_common_pb2'

Please notice this is version 2.2.1 but this also occurs in 3.0

    In [1]: import osi3
    ModuleNotFoundError: No module named 'osi_version_pb2'

My assumption is that this is due to Python 3 not allowing relative imports.
Whats your opinion on this ? Thank you for any feedback. 
BR Jonas Ruebsam

**Comment by jr7** [comment] 2018-06-04 08:56
Maybe somebody can check this on their machine as well. 
So we can  exclude some setup related issues.

**Comment by cszyszka** [comment] 2018-06-06 07:56
@jr7 I'm checking this could you tell which version of protobuf are you using?

**Comment by jr7** [comment] 2018-06-06 08:58
@cszyszka  its 3.5.2

**Comment by cszyszka** [comment] 2018-06-11 13:22
I created new branch which solves the issue. 
https://github.com/OpenSimulationInterface/open-simulation-interface/pull/249

What was needed was:
* move the proto files to osi3 directory.
* edit import statements in definitions to include osi3 package import "osi3/osi_version.proto";
* edit setup.py instalation script 

With this version I can import and work with OSI3. With this test I cab verify it works. 

```python
import osi3.osi_sensordata_pb2
sd = osi3.osi_sensordata_pb2.SensorData()
sd.timestamp.seconds = 1
sd.timestamp.nanos = 2
sd
```

**Comment by LudwigFriedmannBMW** [comment] 2018-08-10 11:46
Hello @cszyszka, since #249 is completed, may this issue also be closed?

**Comment by jr7** [comment] 2018-08-10 13:29
I think this is still an issue, at least the last time I tried  it didn't work..

**Comment by pmai** [comment] 2018-08-10 16:01
Yes the issue is still extant, since the original pull request could not be merged, since this would break the cmake build process. I've fixed the python3 issues within setup.py in #264, so please check whether that really fixes it for you.

**Comment by jr7** [comment] 2018-08-17 09:42
Ok, I tested with the current master and it seems to work  👍

**Closed** 2018-08-17 11:05 UTC
Labels: bug
